import './globals.css'
import Providers from '@/src/app/providers'
import { Roboto } from 'next/font/google'
import AuthProvider from '@/src/components/AuthProvider'
import { Toaster } from '@/src/components/ui/Toaster'

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Muchio Shop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <AuthProvider>
          <Providers>
            {children}
            <Toaster />
          </Providers>
        </AuthProvider>
      </body>
    </html>
  )
}
