import './globals.css'
import Providers from '@/src/app/providers'
import { Roboto } from 'next/font/google'
import AuthProvider from '@/src/components/AuthProvider'
import { Toaster } from '@/src/components/ui/Toaster'
import Head from 'next/head'

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Interstellar',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
      <Head>
        {/* Prevent zoom on mobile input focus */}
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </Head>
      <body>
        <AuthProvider>
          <Providers>
            {children}
            <Toaster />
          </Providers>
        </AuthProvider>
      </body>
    </html>
  )
}
